"""培育流程枚举（ProduceEffectType / ProduceStepType / ProduceResourceType）。

TODO: 当前为严格 Enum，Pydantic 解析时遇到 game.db 中尚未收录的新值会校验失败。
      game data 可独立于程序更新，应改为开放 Enum（str, Enum + _missing_）：
      - 解析层：前缀合法即通过，未知值动态接纳
      - 业务层：仅对 is_known() 的成员做特殊分支
      - UI 层：标签表未命中时 fallback 到 raw value
      可选：CI 从 gakumasu-diff 同步已知成员目录（改善 IDE 补全，非运行时契约）。
"""
from enum import Enum


class ProduceEffectType(Enum):
    """培育流程效果类型（ProduceEffect.produceEffectType）。"""

    AuditionNpcEnhance = 'ProduceEffectType_AuditionNpcEnhance'
    AuditionNpcWeaken = 'ProduceEffectType_AuditionNpcWeaken'
    AuditionParameterBonusMultiple = 'ProduceEffectType_AuditionParameterBonusMultiple'
    AuditionVoteCountUp = 'ProduceEffectType_AuditionVoteCountUp'
    BeforeAuditionRefreshStaminaDown = 'ProduceEffectType_BeforeAuditionRefreshStaminaDown'
    BeforeAuditionRefreshStaminaUp = 'ProduceEffectType_BeforeAuditionRefreshStaminaUp'
    CustomizeProduceCardProducePointDownMultiple = 'ProduceEffectType_CustomizeProduceCardProducePointDownMultiple'
    DanceAddition = 'ProduceEffectType_DanceAddition'
    DanceDown = 'ProduceEffectType_DanceDown'
    DanceGrowthRateAddition = 'ProduceEffectType_DanceGrowthRateAddition'
    DanceGrowthRateDown = 'ProduceEffectType_DanceGrowthRateDown'
    EventActivityProducePointDown = 'ProduceEffectType_EventActivityProducePointDown'
    EventActivityProducePointUp = 'ProduceEffectType_EventActivityProducePointUp'
    EventBusinessVoteCountUp = 'ProduceEffectType_EventBusinessVoteCountUp'
    EventSchoolStaminaDown = 'ProduceEffectType_EventSchoolStaminaDown'
    EventSchoolStaminaUp = 'ProduceEffectType_EventSchoolStaminaUp'
    ExamPermanentAuditionStatusEnchant = 'ProduceEffectType_ExamPermanentAuditionStatusEnchant'
    ExamPermanentLessonStatusEnchant = 'ProduceEffectType_ExamPermanentLessonStatusEnchant'
    ExamStatusEnchant = 'ProduceEffectType_ExamStatusEnchant'
    ExamTurnDown = 'ProduceEffectType_ExamTurnDown'
    ExamTurnUp = 'ProduceEffectType_ExamTurnUp'
    HighScoreGoldAddition = 'ProduceEffectType_HighScoreGoldAddition'
    IdolCardProduceCardCustomizeEnable = 'ProduceEffectType_IdolCardProduceCardCustomizeEnable'
    LessonDanceSpChangeRatePermilAddition = 'ProduceEffectType_LessonDanceSpChangeRatePermilAddition'
    LessonPresentProduceCardRewardCountDown = 'ProduceEffectType_LessonPresentProduceCardRewardCountDown'
    LessonPresentProduceCardRewardCountUp = 'ProduceEffectType_LessonPresentProduceCardRewardCountUp'
    LessonPresentProducePointUp = 'ProduceEffectType_LessonPresentProducePointUp'
    LessonSpChangeRatePermilAddition = 'ProduceEffectType_LessonSpChangeRatePermilAddition'
    LessonSpChangeRatePermilDown = 'ProduceEffectType_LessonSpChangeRatePermilDown'
    LessonVisualSpChangeRatePermilAddition = 'ProduceEffectType_LessonVisualSpChangeRatePermilAddition'
    LessonVocalSpChangeRatePermilAddition = 'ProduceEffectType_LessonVocalSpChangeRatePermilAddition'
    MaxStaminaAddition = 'ProduceEffectType_MaxStaminaAddition'
    MaxStaminaReduceFix = 'ProduceEffectType_MaxStaminaReduceFix'
    MaxStaminaReduceMultiple = 'ProduceEffectType_MaxStaminaReduceMultiple'
    ParameterLimitUp = 'ProduceEffectType_ParameterLimitUp'
    ProduceCardChange = 'ProduceEffectType_ProduceCardChange'
    ProduceCardChangeSelect = 'ProduceEffectType_ProduceCardChangeSelect'
    ProduceCardChangeUpgrade = 'ProduceEffectType_ProduceCardChangeUpgrade'
    ProduceCardDelete = 'ProduceEffectType_ProduceCardDelete'
    ProduceCardDuplicate = 'ProduceEffectType_ProduceCardDuplicate'
    ProduceCardDuplicateUpgrade = 'ProduceEffectType_ProduceCardDuplicateUpgrade'
    ProduceCardExcludeCountUp = 'ProduceEffectType_ProduceCardExcludeCountUp'
    ProduceCardSelectRerollCountUp = 'ProduceEffectType_ProduceCardSelectRerollCountUp'
    ProduceCardUpgrade = 'ProduceEffectType_ProduceCardUpgrade'
    ProduceCustomizeItemUpgrade = 'ProduceEffectType_ProduceCustomizeItemUpgrade'
    ProduceDrinkGetDisable = 'ProduceEffectType_ProduceDrinkGetDisable'
    ProduceDrinkPossessLimitUp = 'ProduceEffectType_ProduceDrinkPossessLimitUp'
    ProduceItemGetDisable = 'ProduceEffectType_ProduceItemGetDisable'
    ProducePointAddition = 'ProduceEffectType_ProducePointAddition'
    ProducePointAdditionDisableTrigger = 'ProduceEffectType_ProducePointAdditionDisableTrigger'
    ProducePointAdditionValueDown = 'ProduceEffectType_ProducePointAdditionValueDown'
    ProducePointAdditionValueUp = 'ProduceEffectType_ProducePointAdditionValueUp'
    ProducePointGetDisable = 'ProduceEffectType_ProducePointGetDisable'
    ProducePointReduceFix = 'ProduceEffectType_ProducePointReduceFix'
    ProducePointReduceMultiple = 'ProduceEffectType_ProducePointReduceMultiple'
    ProducePointReduceValueDown = 'ProduceEffectType_ProducePointReduceValueDown'
    ProducePointReduceValueUp = 'ProduceEffectType_ProducePointReduceValueUp'
    ProducePointSpecify = 'ProduceEffectType_ProducePointSpecify'
    ProduceResultRewardMoneyUp = 'ProduceEffectType_ProduceResultRewardMoneyUp'
    ProduceResultRewardSupportCardEnhancePointUp = 'ProduceEffectType_ProduceResultRewardSupportCardEnhancePointUp'
    ProduceReward = 'ProduceEffectType_ProduceReward'
    ProduceRewardSet = 'ProduceEffectType_ProduceRewardSet'
    ShopPriceDiscountMultiple = 'ProduceEffectType_ShopPriceDiscountMultiple'
    ShopPriceUpMultiple = 'ProduceEffectType_ShopPriceUpMultiple'
    ShopProduceCardDeletePriceDiscountMultiple = 'ProduceEffectType_ShopProduceCardDeletePriceDiscountMultiple'
    ShopProduceCardDeletePriceSpecify = 'ProduceEffectType_ShopProduceCardDeletePriceSpecify'
    ShopProduceCardDeletePriceUpMultiple = 'ProduceEffectType_ShopProduceCardDeletePriceUpMultiple'
    ShopProduceCardPriceDiscountMultiple = 'ProduceEffectType_ShopProduceCardPriceDiscountMultiple'
    ShopProduceCardPriceDiscountMultiplePermanent = 'ProduceEffectType_ShopProduceCardPriceDiscountMultiplePermanent'
    ShopProduceCardPriceUpMultiple = 'ProduceEffectType_ShopProduceCardPriceUpMultiple'
    ShopProduceCardUpgradePriceDiscountMultiple = 'ProduceEffectType_ShopProduceCardUpgradePriceDiscountMultiple'
    ShopProduceCardUpgradePriceSpecify = 'ProduceEffectType_ShopProduceCardUpgradePriceSpecify'
    ShopProduceCardUpgradePriceUpMultiple = 'ProduceEffectType_ShopProduceCardUpgradePriceUpMultiple'
    ShopProduceDrinkPriceDiscountMultiple = 'ProduceEffectType_ShopProduceDrinkPriceDiscountMultiple'
    ShopProduceDrinkPriceUpMultiple = 'ProduceEffectType_ShopProduceDrinkPriceUpMultiple'
    ShopRerollCountUp = 'ProduceEffectType_ShopRerollCountUp'
    StaminaRecoverDisable = 'ProduceEffectType_StaminaRecoverDisable'
    StaminaRecoverFix = 'ProduceEffectType_StaminaRecoverFix'
    StaminaRecoverMultiple = 'ProduceEffectType_StaminaRecoverMultiple'
    StaminaRecoverValueDown = 'ProduceEffectType_StaminaRecoverValueDown'
    StaminaRecoverValueUp = 'ProduceEffectType_StaminaRecoverValueUp'
    StaminaReduceFix = 'ProduceEffectType_StaminaReduceFix'
    StaminaReduceMultiple = 'ProduceEffectType_StaminaReduceMultiple'
    StaminaReduceValueDown = 'ProduceEffectType_StaminaReduceValueDown'
    StaminaReduceValueUp = 'ProduceEffectType_StaminaReduceValueUp'
    StaminaSpecify = 'ProduceEffectType_StaminaSpecify'
    StarAddition = 'ProduceEffectType_StarAddition'
    StarPermilUp = 'ProduceEffectType_StarPermilUp'
    SupportCardEventParameterAdditionValueUp = 'ProduceEffectType_SupportCardEventParameterAdditionValueUp'
    SupportCardEventProbabilityUp = 'ProduceEffectType_SupportCardEventProbabilityUp'
    SupportCardEventProducePointAdditionValueUp = 'ProduceEffectType_SupportCardEventProducePointAdditionValueUp'
    SupportCardEventStaminaRecoverUp = 'ProduceEffectType_SupportCardEventStaminaRecoverUp'
    SupportCardProduceCardUpgradeProbabilityUp = 'ProduceEffectType_SupportCardProduceCardUpgradeProbabilityUp'
    Unknown = 'ProduceEffectType_Unknown'
    VisualAddition = 'ProduceEffectType_VisualAddition'
    VisualDown = 'ProduceEffectType_VisualDown'
    VisualGrowthRateAddition = 'ProduceEffectType_VisualGrowthRateAddition'
    VisualGrowthRateDown = 'ProduceEffectType_VisualGrowthRateDown'
    VocalAddition = 'ProduceEffectType_VocalAddition'
    VocalDown = 'ProduceEffectType_VocalDown'
    VocalGrowthRateAddition = 'ProduceEffectType_VocalGrowthRateAddition'
    VocalGrowthRateDown = 'ProduceEffectType_VocalGrowthRateDown'
    VoteCountAddition = 'ProduceEffectType_VoteCountAddition'


class ProduceStepType(Enum):
    """培育步骤类型（ProduceStepEventSuggestion.stepType 等）。"""

    AuditionFinal = 'ProduceStepType_AuditionFinal'
    AuditionMid1 = 'ProduceStepType_AuditionMid1'
    AuditionMid2 = 'ProduceStepType_AuditionMid2'
    Business = 'ProduceStepType_Business'
    EventActivity = 'ProduceStepType_EventActivity'
    EventSchool = 'ProduceStepType_EventSchool'
    FanPresent = 'ProduceStepType_FanPresent'
    LessonDanceNormal = 'ProduceStepType_LessonDanceNormal'
    LessonDanceSp = 'ProduceStepType_LessonDanceSp'
    LessonVisualNormal = 'ProduceStepType_LessonVisualNormal'
    LessonVisualSp = 'ProduceStepType_LessonVisualSp'
    LessonVocalNormal = 'ProduceStepType_LessonVocalNormal'
    LessonVocalSp = 'ProduceStepType_LessonVocalSp'
    OpenLessonDanceNormal = 'ProduceStepType_OpenLessonDanceNormal'
    OpenLessonDanceNormalStar = 'ProduceStepType_OpenLessonDanceNormalStar'
    OpenLessonDanceSp = 'ProduceStepType_OpenLessonDanceSp'
    OpenLessonDanceSpStar = 'ProduceStepType_OpenLessonDanceSpStar'
    OpenLessonVisualNormal = 'ProduceStepType_OpenLessonVisualNormal'
    OpenLessonVisualNormalStar = 'ProduceStepType_OpenLessonVisualNormalStar'
    OpenLessonVisualSp = 'ProduceStepType_OpenLessonVisualSp'
    OpenLessonVisualSpStar = 'ProduceStepType_OpenLessonVisualSpStar'
    OpenLessonVocalNormal = 'ProduceStepType_OpenLessonVocalNormal'
    OpenLessonVocalNormalStar = 'ProduceStepType_OpenLessonVocalNormalStar'
    OpenLessonVocalSp = 'ProduceStepType_OpenLessonVocalSp'
    OpenLessonVocalSpStar = 'ProduceStepType_OpenLessonVocalSpStar'
    Present = 'ProduceStepType_Present'
    Refresh = 'ProduceStepType_Refresh'
    SelfLessonDanceNormal = 'ProduceStepType_SelfLessonDanceNormal'
    SelfLessonDanceSp = 'ProduceStepType_SelfLessonDanceSp'
    SelfLessonVisualNormal = 'ProduceStepType_SelfLessonVisualNormal'
    SelfLessonVisualSp = 'ProduceStepType_SelfLessonVisualSp'
    SelfLessonVocalNormal = 'ProduceStepType_SelfLessonVocalNormal'
    SelfLessonVocalSp = 'ProduceStepType_SelfLessonVocalSp'
    Unknown = 'ProduceStepType_Unknown'


class ProduceResourceType(Enum):
    """培育奖励资源类型（ProduceEffect.produceResourceType）。"""

    ProduceCard = 'ProduceResourceType_ProduceCard'
    ProduceCustomizeItem = 'ProduceResourceType_ProduceCustomizeItem'
    ProduceDrink = 'ProduceResourceType_ProduceDrink'
    ProduceItem = 'ProduceResourceType_ProduceItem'
    ProducePoint = 'ProduceResourceType_ProducePoint'
    Unknown = 'ProduceResourceType_Unknown'